image: Visual Studio 2015
environment:
  PATH: C:\Ruby25\bin;C:\texlive\bin\win32;%PATH%
cache:
  - C:\texlive
  - vendor/bundle

build: off

install:
  - bundle config --local path vendor/bundle
  - bundle install
  - bundle exec rake setup_appveyor

test_script:
  - bundle exec rake test
