os:
  - osx
  - linux
dist: trusty

language: ruby

addons:
  apt:
    packages:
      - liblz4-tool
      - ghostscript

cache:
  directories:
    - vendor/bundle
    - $HOME/texlive
    - $HOME/.texlive
    - $HOME/Library/Caches/Homebrew

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export PATH=$PATH:$HOME/texlive/bin/x86_64-darwin;
    else
      export PATH=$PATH:$HOME/texlive/bin/x86_64-linux;
    fi

install:
  - bundle install --without production --deployment
  - bundle exec rake setup_travis

script:
  - bundle exec rake test
